// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Projekat.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20220320203401_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Proizvod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cena")
                        .HasColumnType("int")
                        .HasColumnName("Cena");

                    b.Property<int>("kolicina")
                        .HasColumnType("int")
                        .HasColumnName("Kolicina");

                    b.Property<string>("naziv")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Naziv");

                    b.Property<int?>("redID")
                        .HasColumnType("int");

                    b.Property<int?>("skladisteID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("redID");

                    b.HasIndex("skladisteID");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Models.Red", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kategorija")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Kategorija");

                    b.Property<int?>("supermarketID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("supermarketID");

                    b.ToTable("Red");
                });

            modelBuilder.Entity("Models.Skladiste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("supermarketID")
                        .HasColumnType("int");

                    b.Property<int>("velicina")
                        .HasColumnType("int")
                        .HasColumnName("Velicina");

                    b.HasKey("ID");

                    b.HasIndex("supermarketID");

                    b.ToTable("Skladiste");
                });

            modelBuilder.Entity("Models.Supermarket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("grad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Grad");

                    b.HasKey("ID");

                    b.ToTable("Supermarket");
                });

            modelBuilder.Entity("Models.Proizvod", b =>
                {
                    b.HasOne("Models.Red", "red")
                        .WithMany("proizvodi")
                        .HasForeignKey("redID");

                    b.HasOne("Models.Skladiste", "skladiste")
                        .WithMany("proizvod")
                        .HasForeignKey("skladisteID");

                    b.Navigation("red");

                    b.Navigation("skladiste");
                });

            modelBuilder.Entity("Models.Red", b =>
                {
                    b.HasOne("Models.Supermarket", "supermarket")
                        .WithMany("redovi")
                        .HasForeignKey("supermarketID");

                    b.Navigation("supermarket");
                });

            modelBuilder.Entity("Models.Skladiste", b =>
                {
                    b.HasOne("Models.Supermarket", "supermarket")
                        .WithMany("skladista")
                        .HasForeignKey("supermarketID");

                    b.Navigation("supermarket");
                });

            modelBuilder.Entity("Models.Red", b =>
                {
                    b.Navigation("proizvodi");
                });

            modelBuilder.Entity("Models.Skladiste", b =>
                {
                    b.Navigation("proizvod");
                });

            modelBuilder.Entity("Models.Supermarket", b =>
                {
                    b.Navigation("redovi");

                    b.Navigation("skladista");
                });
#pragma warning restore 612, 618
        }
    }
}
